package tn.esprit.Models;

public enum ReportReason {
    MINEUR_IMPLIQUE,
    HARCELEMENT,
    SUICIDE_AUTOMUTILATION,
    CONTENU_VIOLENT,
    VENTE_ARTICLES_RESTREINTS,
    CONTENU_ADULTE,
    ARNAQUE_FAUSSE_INFORMATION,
    CONTENU_NON_DESIRE
}

